"""create_onboarding_status_table

Revision ID: 7623f1479df1
Revises: 8d005f145013
Create Date: 2025-09-22 14:17:19.356154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7623f1479df1'
down_revision: Union[str, None] = '8d005f145013'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('onboarding_status',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('current_stage', sa.String(length=255), nullable=True),
    sa.Column('current_step', sa.String(length=255), nullable=True),
    sa.Column('asset_discovery_configured', sa.Boolean(), nullable=False),
    sa.Column('case_management_configured', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_onboarding_status_tenant_id'), 'onboarding_status', ['tenant_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_onboarding_status_tenant_id'), table_name='onboarding_status')
    op.drop_table('onboarding_status')
    # ### end Alembic commands ###
