"""Initial migration - create all tables

Revision ID: 7d179d96fe44
Revises: 
Create Date: 2025-09-25 10:53:02.422863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d179d96fe44'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_history',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_history_created_at'), 'chat_history', ['created_at'], unique=False)
    op.create_index(op.f('ix_chat_history_tenant_id'), 'chat_history', ['tenant_id'], unique=False)
    op.create_table('integration_content',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('integration_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('heading', sa.Text(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('default', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('onboarding_content',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('stage', sa.String(length=100), nullable=False),
    sa.Column('step', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('heading', sa.Text(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stage', 'step', 'status', name='uq_stage_step_status')
    )
    op.create_index(op.f('ix_onboarding_content_stage'), 'onboarding_content', ['stage'], unique=False)
    op.create_index(op.f('ix_onboarding_content_status'), 'onboarding_content', ['status'], unique=False)
    op.create_index(op.f('ix_onboarding_content_step'), 'onboarding_content', ['step'], unique=False)
    op.create_table('onboarding_status',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('current_stage', sa.String(length=255), nullable=True),
    sa.Column('current_step', sa.String(length=255), nullable=True),
    sa.Column('asset_discovery_configured', sa.Boolean(), nullable=False),
    sa.Column('case_management_configured', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_onboarding_status_tenant_id'), 'onboarding_status', ['tenant_id'], unique=True)
    op.create_table('roles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_table('teammate_behaviour',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.String(length=255), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teammate_behaviour_id'), 'teammate_behaviour', ['id'], unique=False)
    op.create_index(op.f('ix_teammate_behaviour_tenant_id'), 'teammate_behaviour', ['tenant_id'], unique=False)
    op.create_table('role_tasks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('taskname', sa.String(length=255), nullable=False),
    sa.Column('role_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_role_tasks_role_id'), 'role_tasks', ['role_id'], unique=False)
    op.create_index(op.f('ix_role_tasks_taskname'), 'role_tasks', ['taskname'], unique=False)
    op.create_table('tenant_roles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(length=255), nullable=False),
    sa.Column('role_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', name='uq_tenant_role')
    )
    op.create_index(op.f('ix_tenant_roles_role_id'), 'tenant_roles', ['role_id'], unique=False)
    op.create_index(op.f('ix_tenant_roles_tenant_id'), 'tenant_roles', ['tenant_id'], unique=False)
    op.create_table('tenant_tasks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(length=255), nullable=False),
    sa.Column('role_task_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['role_task_id'], ['role_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenant_tasks_role_task_id'), 'tenant_tasks', ['role_task_id'], unique=False)
    op.create_index(op.f('ix_tenant_tasks_tenant_id'), 'tenant_tasks', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tenant_tasks_tenant_id'), table_name='tenant_tasks')
    op.drop_index(op.f('ix_tenant_tasks_role_task_id'), table_name='tenant_tasks')
    op.drop_table('tenant_tasks')
    op.drop_index(op.f('ix_tenant_roles_tenant_id'), table_name='tenant_roles')
    op.drop_index(op.f('ix_tenant_roles_role_id'), table_name='tenant_roles')
    op.drop_table('tenant_roles')
    op.drop_index(op.f('ix_role_tasks_taskname'), table_name='role_tasks')
    op.drop_index(op.f('ix_role_tasks_role_id'), table_name='role_tasks')
    op.drop_table('role_tasks')
    op.drop_index(op.f('ix_teammate_behaviour_tenant_id'), table_name='teammate_behaviour')
    op.drop_index(op.f('ix_teammate_behaviour_id'), table_name='teammate_behaviour')
    op.drop_table('teammate_behaviour')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_onboarding_status_tenant_id'), table_name='onboarding_status')
    op.drop_table('onboarding_status')
    op.drop_index(op.f('ix_onboarding_content_step'), table_name='onboarding_content')
    op.drop_index(op.f('ix_onboarding_content_status'), table_name='onboarding_content')
    op.drop_index(op.f('ix_onboarding_content_stage'), table_name='onboarding_content')
    op.drop_table('onboarding_content')
    op.drop_table('integration_content')
    op.drop_index(op.f('ix_chat_history_tenant_id'), table_name='chat_history')
    op.drop_index(op.f('ix_chat_history_created_at'), table_name='chat_history')
    op.drop_table('chat_history')
    # ### end Alembic commands ###
