"""create_tenant_role_and_tenant_tasks_tables

Revision ID: 8d005f145013
Revises: e6362565764e
Create Date: 2025-09-22 07:16:16.847810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d005f145013'
down_revision: Union[str, None] = 'e6362565764e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenant_roles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(length=255), nullable=False),
    sa.Column('role_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', name='uq_tenant_role')
    )
    op.create_index(op.f('ix_tenant_roles_role_id'), 'tenant_roles', ['role_id'], unique=False)
    op.create_index(op.f('ix_tenant_roles_tenant_id'), 'tenant_roles', ['tenant_id'], unique=False)
    op.create_table('tenant_tasks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(length=255), nullable=False),
    sa.Column('role_task_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['role_task_id'], ['role_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenant_tasks_role_task_id'), 'tenant_tasks', ['role_task_id'], unique=False)
    op.create_index(op.f('ix_tenant_tasks_tenant_id'), 'tenant_tasks', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tenant_tasks_tenant_id'), table_name='tenant_tasks')
    op.drop_index(op.f('ix_tenant_tasks_role_task_id'), table_name='tenant_tasks')
    op.drop_table('tenant_tasks')
    op.drop_index(op.f('ix_tenant_roles_tenant_id'), table_name='tenant_roles')
    op.drop_index(op.f('ix_tenant_roles_role_id'), table_name='tenant_roles')
    op.drop_table('tenant_roles')
    # ### end Alembic commands ###
