"""add_heading_field_to_onboarding_content

Revision ID: b0ae8e20e068
Revises: 299c445fe504
Create Date: 2025-09-24 09:10:24.059475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0ae8e20e068'
down_revision: Union[str, None] = '299c445fe504'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('onboarding_content', sa.Column('heading', sa.Text(), nullable=True))
    op.alter_column('onboarding_content', 'text',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('onboarding_content', 'text',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('onboarding_content', 'heading')
    # ### end Alembic commands ###
