"""create_teammate_behaviour_table

Revision ID: f7de63f26beb
Revises: 1ec7946c17c0
Create Date: 2025-09-19 13:25:10.963951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7de63f26beb'
down_revision: Union[str, None] = '1ec7946c17c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
